language: r
sudo: false
cache: packages
r:
- release
- devel
r_packages:
- devtools
- animation
r_github_packages:
- jimhester/covr
- hadley/pkgdown
addons:
  apt:
    packages:
      - imagemagick
env:
  matrix:
  - _R_CHECK_LENGTH_1_CONDITION_=true
  global:
    secure: efki/PoCvROHC5GMOWqL3hiYeU/no71mnw927ZLF/D0eo3L0aBjT6533KWy3S8w+kg4ilgZzoS5/Nu6PuVFmfPmOiXKj95ZZVkuHDjnAiBFPsowneruOAYNMpwGlM1A3Z3T6jTjtX+FtvlgukhVNrkNoXFy5SmZ5pclic0Z7zfM=
before_script:
- R --no-save <<< 'library("devtools"); document()'
after_success:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" && "${TRAVIS_R_VERSION_STRING}"
  == "release" ]]; then bash .github/deploy.sh; fi;
- if [[ "${TRAVIS_R_VERSION_STRING}" == "release" ]]; then Rscript -e 'covr::coveralls()'; fi;
