language: R
sudo: required
cache: packages
warnings_are_errors: false
r_check_args: "--as-cran --run-donttest"
env:
  global:
    - _R_CHECK_TIMINGS_=0
    - secure: "e2QLomaUqNvpHnGNdBXS4VO2/UWokrKl9UgYrqWo+fhpXaJiJuONNPNL44BuWZR2Cy7noTHrevVbTKBkGpqJR42mkjzcjd6qyR1Ctiveir+84/HTtmexouIUn5OFRH5dgyt/gquld31RlHlSYoKho3nZ7D7SnVExov9tp2FGRhU="

r_github_packages:
  - berndbischl/parallelMap
  - jakobbossek/smoof
  - mlr-org/mlr

r_binary_packages:
  - akima
  - assertthat
  - chron
  - cmaes
  - crayon
  - data.table
  - DBI
  - DiceOptim
  - dplyr
  - earth
  - emoa
  - GGally
  - ggplot2
  - ggvis
  - gridExtra
  - htmltools
  - httpuv
  - kernlab
  - kknn
  - lazyeval
  - mboost
  - mco
  - multcomp
  - nnet
  - party
  - plyr
  - plotrix
  - randomForest
  - RColorBrewer
  - reshape2
  - rpart
  - shiny
  - testthat
  - zoo

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test -y
    - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
    - Rscript -e 'install.packages("nlme", lib="/home/travis/R-bin/lib/R/library/")'
before_script:
    - curl -L https://raw.githubusercontent.com/mllg/travis-r-tools/master/update-packages.r -o /tmp/update-packages.r
    - Rscript /tmp/update-packages.r

notifications:
  email:
    recipients:
      - bernd_bischl@gmx.net
      - j.bossek@gmail.com
      - daniel.horn@tu-dortmund.de
      - michellang@gmail.com
      - code@jakob-r.de
    on_success: change
    on_failure: always
